version: "2.0"
services:
  mysql_ctnr:
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=mysql
      - MYSQL_ROOTPASSWORD=mysql
      - MYSQL_DATABASE=docapp
  
  doctorapp:
    build: .
    ports:
      - "8080:8080"
    expose: 
      - "8080"
     